on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm i
      - run: pnpm build
      - run: node packages/coverage-viz/build.mjs
      - run: node packages/coverage-viz/build-monaco.mjs
      - run: pnpm -C packages/coverage-viz build-site
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: packages/coverage-viz/site

  deploy-cloudflare-pages:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: site
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cov
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
